### ISSUE TITLE
error with journalctl

### ISSUE THREAD

**Issue by truesamurai** [mzfr/go-gtfo#1]
go-gtfo -b nmap works fine, but i have an error when i run:
go-gtfo -b journalctl

the error is:

./go-gtfo -b journalctl
    _  _               _      __
  _| || |_            | |    / _|
 |_  __  _|     __ _  | |_  | |_    ___
  _| || |_     / _` | | __| |  _|  / _ \
 |_  __  _|   | (_| | | |_  | |   | (_) |
   |_||_|      \__, |  \__| |_|    \___/
                __/ |
               |___/
panic: interface conversion: interface {} is string, not map[interface {}]interface {}

goroutine 1 [running]:
main.gtfobins(0x7ffe2597552e, 0xa)
	/root/go/src/github.com/mzfr/go-gtfo/main.go:70 +0xda3
main.main()
	/root/go/src/github.com/mzfr/go-gtfo/main.go:96 +0x1f3

**Comment by mzfr** [comment]
hey @sh1va73 thanks for reporting this. I have pushed the fix for now. 

I will release the new version once the this [PR](https://github.com/common-nighthawk/go-figure/pull/12) is merged and figure package is updated to include colors.

But for now it's fixed and once again thanks for reporting it :)
